
% Wrapper for FSL's convertwarp, to concatenate multiple affine transforms
% and nonlinear warps. Generates .json metadata for output warp and
% jacobian files.
%
% fpp.fsl.concatWarp(outputWarp,referencePath,varargin)
%
% Variable arguments: premat, warp1, midmat, warp2, postmat, jacobian,
% jmin, jmax, constrainj, abs, rel, absout, relat (see FSL's convertwarp
% for further explanation)

function concatWarp(outputWarp,referencePath,varargin)

% Define variable defaults
jsonOpts.indent = '\t';     % Use tab indentation for JSON outputs

% Edit variable arguments.  Note: optInputs checks for proper input.
varArgList = {'premat','warp1','midmat','warp2','postmat','jacobian','jmin','jmax',...
    'constrainj','abs','rel','absout','relout'};
indArgIsBoolean = 9:13;
for i=1:length(varArgList)
    argVal = fpp.util.optInputs(varargin,varArgList{i});
    if ~isempty(argVal)
        if ischar(argVal)
            eval([varArgList{i} ' = argVal;']);
        else
            eval([varArgList{i} ' = num2str(argVal);']);
        end
    else
        eval([varArgList{i} ' = [];']);
    end
end

cmd = ['convertwarp --out=' outputWarp ' --ref=' referencePath];

% Add non-boolean additional variables
for i=setdiff(1:length(varArgList),indArgIsBoolean)
    if ~isempty(eval(varArgList{i}))
        eval(['cmd = [cmd '' --' varArgList{i} '=' eval(varArgList{i}) '''];']);
    end
end
% Add boolean additional variables
for i=indArgIsBoolean
    if ~isempty(eval(varArgList{i}))
        eval(['cmd = [cmd '' --' varArgList{i} '''];']);
    end
end

% Run convert_xfm command
fpp.util.system(cmd);

% Write .json file for outputs, json files for relevant inputs exist.
if ~((~isempty(premat) && ~isempty(fpp.bids.getMetadata(premat))) || ...
        (~isempty(warp1) && ~isempty(fpp.bids.getMetadata(warp1))) || ...
        (~isempty(midmat) && ~isempty(fpp.bids.getMetadata(midmat))) || ...
        (~isempty(warp2) && ~isempty(fpp.bids.getMetadata(warp2))) || ...
        (~isempty(postmat) && ~isempty(fpp.bids.getMetadata(postmat))))
    
    % Output warp
    jsonData.Type = 'Nonlinear';
    jsonData.Software = 'FNIRT';
    jsonData.Invertible = true;
    jsonData.CommandLine = cmd;
    jsonData.Description = 'Warp coefficient file generated by FNIRT.';
    if ~isempty(premat)
        jsonDataPremat = fpp.bids.getMetadata(premat);
        jsonData.FromFile = jsonDataPremat.FromFile;
    elseif ~isempty(warp1)
        jsonDataWarp1 = fpp.bids.getMetadata(warp1);
        jsonData.FromFile = jsonDataWarp1.FromFile;
    elseif ~isempty(midmat)
        jsonDataMidmat = fpp.bids.getMetadata(midmat);
        jsonData.FromFile = jsonDataMidmat.FromFile;
    elseif ~isempty(warp2)
        jsonDataWarp2 = fpp.bids.getMetadata(warp2);
        jsonData.FromFile = jsonDataWarp2.FromFile;
    elseif ~isempty(postmat)
        jsonDataPostmat = fpp.bids.getMetadata(postmat);
        jsonData.FromFile = jsonDataPostmat.FromFile;
    end
    if ~isempty(postmat)
        jsonDataPostmat = fpp.bids.getMetadata(postmat);
        jsonData.FromFile = jsonDataPostmat.ToFile;
    elseif ~isempty(warp2)
        jsonDataWarp2 = fpp.bids.getMetadata(warp2);
        jsonData.FromFile = jsonDataWarp2.ToFile;
    elseif ~isempty(midmat)
        jsonDataMidmat = fpp.bids.getMetadata(midmat);
        jsonData.FromFile = jsonDataMidmat.ToFile;
    elseif ~isempty(warp1)
        jsonDataWarp1 = fpp.bids.getMetadata(warp1);
        jsonData.FromFile = jsonDataWarp1.ToFile;
    elseif ~isempty(premat)
        jsonDataPremat = fpp.bids.getMetadata(premat);
        jsonData.FromFile = jsonDataPremat.ToFile;
    end
    bids.util.jsonencode(outputXfmJsonPath,jsonData,jsonOpts);
    
    % Warp jacobian
    if ~isempty(jacobian)
        jsonData.Description = 'Jacobian file generated by FNIRT.';
        bids.util.jsonencode(fpp.bids.jsonPath(jacobian),jsonData,jsonOpts);
    end
end

end