%
% fpp.anat.postproc(subjID,inputT1Path,fsSubDir,varargin)
%
% Script to post-process anatomical data after Freesurfer reconstruction. 
% Includes gifti conversion, generation of midthickness, inflated, and 
% vinflated surfaces, registration and resampling to fsLR space, etc.
%
% Arguments:
% - subjID (string): subject ID
% - inputT1Path (string): path to preprocessed anatomical image
% - fsSubDir (string): freesurfer subject directory for this subject
% 
% Optional arguments:
% - overwrite (boolean): whether to overwrite existing outputs
%
% This script is a modified version of the Human Connectome Project's
% PostFreesurfer pipeline (https://www.humanconnectome.org/software/hcp-mr-pipelines;
% Glasser et al. 2013, "The minimal preprocessing pipelines for the Human 
% Connectome Project").

function postproc(subjID,inputT1Path,fsSubDir,varargin)

% TODO:
% - Convert Multimodal parcellation to individual space (surf and vol)
% - Avoid writing in SUBJECTS_DIR; copy to anatPreprocDir first
%   - SPECIFICALLY: For orig.mgz, convert to a file in anat dir and DEFINE
%     JSON FILE before generating registration files
% - Add RawSources metadata
% - Add json files for S1200 atlas inputs
% - Convert HCP-style LUT files to BIDS-style dseg.tsv files for all
%   segmentations

% Check system configuration
fpp.util.checkConfig;

% Use tab indentation for JSON outputs
jsonOpts.indent = '\t';

% Variable arguments
overwrite = 0;

% Edit variable arguments.  Note: optInputs checks for proper input.
varArgList = {'overwrite'};
for i=1:length(varArgList)
    argVal = fpp.util.optInputs(varargin,varArgList{i});
    if ~isempty(argVal)
        eval([varArgList{i} ' = argVal;']);
    end
end

if ~exist(inputT1Path,'file')
    error('inputT1Path does not exist.')
end
if ~exist(fsSubDir,'dir')
    error('fsSubDir does not exist.')
end

% Define directories
[anatPreprocDir,~,~] = fpp.util.fileParts(inputT1Path);
if isempty(anatPreprocDir), anatPreprocDir = pwd; end
[fppFuncDir,~,~]		= fileparts(mfilename('fullpath'));			% path to the directory containing this script
tmp = dir([fppFuncDir '/../../data']);
dataDir = tmp(1).folder;

% Check if output exists.
finalOutputPath = fpp.bids.changeName(inputT1Path,{'space','den','desc','res'},{'fsLR','32k',[],[]},'brain','.spec');
if exist(finalOutputPath,'file') && ~overwrite
    return;
end

% Write json file with density info
densityJsonPath = [anatPreprocDir '/tmpDensity102941.json'];
fid = fopen(densityJsonPath,'wt');
fprintf(fid, ['{"native":"High-density native surface mesh generated by Freesurefer",'...
    '"32K":"32K vertices per hemisphere, coordinates aligned with fsLR space",'...
    '"164K":"164K vertices per hemisphere"}']);
fclose(fid);
densityJson = bids.util.jsondecode(densityJsonPath);
fpp.util.system(['rm -rf ' densityJsonPath]);

% Freesurfer and Connectome Workbench names
hemis = {'lh','rh'};
Hemis = {'L','R'};
structures = {'CORTEX_LEFT','CORTEX_RIGHT'};

surfaces = {'white','pial'};
types = {'ANATOMICAL','ANATOMICAL'};
types2 = {'GRAY_WHITE','PIAL'};

shapes = {'sulc','thickness','curv'};
mapNames = {'Sulc','Thickness','Curvature'};

parcs = {'wmparc','aparc+aseg','aparc.a2009s+aseg'};    % Volumetric parcs

% Paths
mriDir = [fsSubDir '/mri'];
surfDir = [fsSubDir '/surf'];

origPath = [mriDir '/orig.nii.gz'];
crasXfm = [mriDir '/c_ras.mat'];

inputT2Path = fpp.bids.changeName(inputT1Path,'','','T2w','.nii.gz');
if ~exist(inputT2Path,'file'), inputT2Path = []; end

midthickPaths{1} = fpp.bids.changeName(inputT1Path,{'hemi','den','desc','res'},{'L','native',[],[]},'midthickness','.surf.gii');
midthickPaths{2} = fpp.bids.changeName(midthickPaths{1},'hemi','R');
% individual2FsnativeXfm = [anatPreprocDir '/sub-' subjID '_from-individual_to-fsnative_mode-image_xfm.mat'];
% fsnative2IndividualXfm = [anatPreprocDir '/sub-' subjID '_from-fsnative_to-individual_mode-image_xfm.mat'];
individual2FsnativeXfm = fpp.bids.changeName(inputT1Path,{'desc','space','from','to','mode'},...
    {[],[],'individual','fsnative','image'},'xfm','.mat');
fsnative2IndividualXfm = fpp.bids.changeName(individual2FsnativeXfm,{'from','to'},{'fsnative','individual'});

for h=1:2
    fsLRSpherePaths{h}{1} = [anatPreprocDir '/hemi-' Hemis{h} '_space-fsLR_den-32k_sphere.surf.gii'];
    fsLRSpherePaths{h}{2} = strrep(fsLRSpherePaths{h}{1},'den-32k','den-164k');
end

standardName = 'MNI152NLin6ASym';
standardPath2mmBrain = [anatPreprocDir '/space-MNI152Nlin6Asym_res-2_desc-brain_T1w.nii.gz'];



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 1: Register fsnative to individual anatomical space
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 1, Register fsnative to individual        - ' subjID]);
fpp.fs.mriConvert(strrep(origPath,'.nii.gz','.mgz'),origPath);  % Convert orig to .nii.gz
fpp.fsl.flirt(inputT1Path,origPath,individual2FsnativeXfm,[],'dof',6);
fpp.fsl.invertXfm(individual2FsnativeXfm,fsnative2IndividualXfm);



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 2: Convert volumetric files to individual
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 2, Convert volumetric files to individual - ' subjID]);
fpp.util.system(['cp ' dataDir '/desc-freesurfer_lut.txt ' anatPreprocDir '/desc-freesurfer_lut.txt']);
% Convert parcs to individual
for p=1:length(parcs)
    inputPath = [mriDir '/' parcs{p} '.nii.gz'];
    outputPath = fpp.bids.changeName(inputT1Path,{'desc','res'},{parcs{p},[]},'dseg','.nii.gz');
    fpp.fs.mriConvert(strrep(inputPath,'.nii.gz','.mgz'),inputPath);  % Convert orig to .nii.gz
    fpp.fsl.moveImage(inputPath,inputT1Path,outputPath,fsnative2IndividualXfm,'interp','nn');
    fpp.wb.command('volume-label-import',outputPath,[anatPreprocDir '/desc-freesurfer_lut.txt'],outputPath,'-drop-unused-labels');
    if strcmp(parcs{p},'wmparc'), wmPath = outputPath; end
    jsonData.Sources = fpp.bids.removeBidsDir(inputPath);
    jsonData.SpatialRef = fpp.bids.removeBidsDir(inputT1Path);
    bids.util.jsonencode(fpp.bids.jsonPath(outputPath),jsonData);
end
% Define brain mask
maskPath = fpp.bids.changeName(inputT1Path,{'desc','res'},{'brainFS',[]},'mask','.nii.gz');
fpp.fsl.maths(wmPath,'-bin -dilD -dilD -dilD -ero -ero',maskPath);
fpp.wb.command('volume-fill-holes',maskPath,[],maskPath);
fpp.fsl.maths(maskPath,'-bin',maskPath);
% Convert vmPFCLarge ROI from MNI to individual, add to FS brain mask
% Goal: ensure that none of vmPFC gray matter is excluded.
standard2IndividualXfmInit = fpp.bids.changeName(inputT1Path,{'from','to','mode','space','desc','res'},...
    {standardName,'individual','image','','nonlinearInit',[]},'xfm','.nii.gz');
vmPFCMaskPathStd = [dataDir '/space-MNI152Nlin6Asym_res-2_desc-vmPFCLarge_mask.nii.gz'];
vmPFCMaskPath = fpp.bids.changeName(inputT1Path,{'desc','res'},{'vmPFCLarge',[]},'mask','.nii.gz');
fpp.fsl.moveImage(vmPFCMaskPathStd,inputT1Path,vmPFCMaskPath,[],'warp',...
    standard2IndividualXfmInit,'rel',1,'interp','nn');
fpp.fsl.maths(maskPath,['-add ' vmPFCMaskPath ' -bin'],maskPath);
% Mask brain images
fpp.fsl.maths(inputT1Path,['-mul ' maskPath],fpp.bids.changeName(inputT1Path,'desc','preprocBrain'));
if exist(inputT2Path,'file')
    fpp.fsl.maths(inputT2Path,['-mul ' maskPath],fpp.bids.changeName(inputT2Path,'desc','preprocBrain'));
end
% Generate dilated brain mask to convert to func template space
fpp.fsl.maths(maskPath,'-dilD',fpp.bids.changeName(maskPath,'desc','brainFSdil1'));



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 3: Refine MNI registration
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 3, Refine MNI registration                - ' subjID]);
fpp.util.system(['cp ' strrep(standardPath2mmBrain,anatPreprocDir,dataDir) ' ' standardPath2mmBrain]);  % Copy 2mm MNI image
% ...



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 4: Process subcortical ROIs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 4, Process subcortical ROIs               - ' subjID]);
% ...



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 5: Convert surfaces to gifti
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 5, Convert surfaces to GIFTI              - ' subjID]);
fpp.util.writeCras([mriDir '/brain.finalsurfs.mgz'],crasXfm);   % Make c_ras.mat
for h=1:2
    % White/pial surfaces
    for s=1:length(surfaces)
        inputPath = [surfDir '/' hemis{h} '.' surfaces{s}];
        outputPath = fpp.bids.changeName(midthickPaths{h},[],[],surfaces{s});
        fpp.util.convertToGii(inputPath,outputPath,structures{h},crasXfm,{'Sources','Density'},...
            {fpp.bids.removeBidsDir(inputPath),densityJson}); 	% fsnative space
    end
    % Spherical surface
    inputPath = [surfDir '/' hemis{h} '.sphere'];
    spherePaths{h} = fpp.bids.changeName(midthickPaths{h},'','','sphere');
    fpp.util.convertToGii(inputPath,spherePaths{h},{structures{h},'SPHERICAL'},[],'Sources',fpp.bids.removeBidsDir(inputPath));
    % Sphere registered to fsaverage
    inputPath = [surfDir '/' hemis{h} '.sphere.reg'];
    sphereRegPaths{h} = fpp.bids.changeName(midthickPaths{h},{'desc'},{'reg2fsavg'},'sphere');
    fpp.util.convertToGii(inputPath,sphereRegPaths{h},{structures{h},'SPHERICAL'},[],'Sources',fpp.bids.removeBidsDir(inputPath));
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 6: Generate midthickness / inflated surfaces
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 6, Generate mid-thickness/inflated surfs  - ' subjID]);
for h=1:2
    % Generate mid-thickness surface by averaging white/pial
    fpp.wb.command('surface-average',[],[],midthickPaths{h},['-surf ' fpp.bids.changeName(midthickPaths{h},[],[],'pial')...
        ' -surf ' fpp.bids.changeName(midthickPaths{h},[],[],'white')]);
    fpp.wb.command('set-structure',midthickPaths{h},structures{h},[],...
        '-surface-type ANATOMICAL -surface-secondary-type MIDTHICKNESS');
    % Generate inflated and very inflated surface, using HCP method
    [~,nVerts] = fpp.util.system(['wb_command -file-information ' midthickPaths{h} ...
         ' | grep ''Number of Vertices:'' | cut -f2 -d: | tr -d ''[:space:]''']);
    nVerts = str2num(strtrim(nVerts));
    nativeInflationScale = .75*nVerts/32492; % HCP fsLR32k used 0.75. Scale this for native mesh density
    fpp.wb.command('surface-generate-inflated',midthickPaths{h},fpp.bids.changeName(midthickPaths{h},[],[],'inflated'),...
        fpp.bids.changeName(midthickPaths{h},[],[],'vinflated'),['-iterations-scale ' num2str(nativeInflationScale)]);
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 7: Convert shape files to gifti
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 7, Convert shape files to GIFTI           - ' subjID]);
for h=1:2
    for s=1:length(shapes)
        inputPath = [surfDir '/' hemis{h} '.' shapes{s}];
        inputSurfPath = [surfDir '/' hemis{h} '.white'];
        outputPath = fpp.bids.changeName(midthickPaths{h},'','',shapes{s},'.shape.gii');
        fpp.util.convertToGii({inputPath,inputSurfPath},outputPath,structures{h},[],{'Sources','Density','SpatialRef'},...
            {fpp.bids.removeBidsDir(inputPath),densityJson,midthickPaths{h}});
        fpp.wb.command('metric-math',[],'var * -1',outputPath,['-var var ' outputPath]);
        fpp.wb.command('set-map-names',outputPath,[],[],['-map 1 ' subjID '_' Hemis{h} '_' mapNames{s}]);
        fpp.wb.command('metric-palette',outputPath,'MODE_AUTO_SCALE_PERCENTAGE',[],...
            '-pos-percent 2 98 -palette-name Gray_Interp -disp-pos true -disp-neg true -disp-zero true');
        eval([shapes{s} 'Paths{h} = outputPath;']);
    end
    % Thickness-specific operations (HCP)
    outputPath = thicknessPaths{h};
    fpp.wb.command('metric-math',[],'abs(thickness)',outputPath,['-var thickness ' outputPath]);
    fpp.wb.command('metric-palette',outputPath,'MODE_AUTO_SCALE_PERCENTAGE',[],...
        '-pos-percent 4 96 -interpolate true -palette-name videen_style -disp-pos true -disp-neg false -disp-zero false');
    % Define GM mask
    maskPaths{h} = fpp.bids.changeName(outputPath,'desc','cortex','mask');
    fpp.wb.command('metric-math',[],'thickness > 0',maskPaths{h},['-var thickness ' outputPath]);
    fpp.wb.command('metric-fill-holes',midthickPaths{h},maskPaths{h},maskPaths{h});
    fpp.wb.command('metric-remove-islands',midthickPaths{h},maskPaths{h},maskPaths{h});
    fpp.wb.command('set-map-names',maskPaths{h},[],[],['-map 1 ' subjID '_' Hemis{h} '_ROI']);
    % Dilate thickness and curvature
    fpp.wb.command('metric-dilate',outputPath,[midthickPaths{h} ' 10'],outputPath,'-nearest');
    outputPath2 = strrep(outputPath,'thickness.shape','curv.shape');
    fpp.wb.command('metric-dilate',curvPaths{h},[midthickPaths{h} ' 10'],curvPaths{h},'-nearest');
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 8: Convert Freesurfer parcellations to gifti
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
parcs = {'aparc','aparc.a2009s'};
fprintf('%s\n',['Step 8, Convert parcellations to GIFTI         - ' subjID]);
for h=1:2
    for p=1:length(parcs)
        inputPath = [fsSubDir '/label/' hemis{h} '.' parcs{p} '.annot'];
        inputSurfPath = [surfDir '/' hemis{h} '.white'];
        outputPath = fpp.bids.changeName(midthickPaths{h},'desc',parcs{p},'dseg','.label.gii');
        fpp.util.convertToGii({inputPath,inputSurfPath},outputPath,structures{h},[],{'Sources','Density','SpatialRef'},...
            {fpp.bids.removeBidsDir(inputPath),densityJson,midthickPaths{h}});
        fpp.wb.command('set-map-names',outputPath,[],[],['-map 1 ' subjID '_' Hemis{h} '_' parcs{p}]);
        fpp.wb.command('gifti-label-add-prefix',outputPath,['"' Hemis{h} '_"'],outputPath);
        parcPaths{h}{p} = outputPath;
    end
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 9: Register fsnative to fsLR
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 9, Register fsnative to fsLR              - ' subjID]);
% fpp.util.system(['cp ' dataDir '/*_space-fs* ' anatPreprocDir '/']);  % Old version, doesn't copy json files
atlasFiles = dir([dataDir '/*_space-fs*']);
for f=1:length(atlasFiles)    % Copy fsLR atlas files
    fpp.util.copyImageAndJson([dataDir '/' atlasFiles(f).name],[anatPreprocDir '/' atlasFiles(f).name]);
end
fid = fopen([anatPreprocDir '/desc-medialwall_lut.txt'],'wt'); % Write MedialWall LUT
fprintf(fid,'%s\n','MEDIAL.WALL');  fprintf(fid,'%s\n','1 19 19 19 255');   fclose(fid);
msmDir = [anatPreprocDir '/MSMSulc'];
mkdir(msmDir);
for h=1:2
    % Concatenate fsaverage reg with fsaverage -> fsLR reg from HCP pipeline
    sphereRegFsLRPaths{h} = fpp.bids.changeName(sphereRegPaths{h},'desc','reg2fsLR');   % Final MSMSulc version
    sphereRegFsLRVertAreaPaths{h} = fpp.bids.changeName(sphereRegFsLRPaths{h},[],[],'area');
    sphereRegFsLRInitPaths{h} = fpp.bids.changeName(sphereRegPaths{h},'desc','reg2fsLRFreesurfer');
    sphereRegFsLRInitAffinePaths{h} = fpp.bids.changeName(sphereRegPaths{h},'desc','reg2fsLRFreesurferAffine');
    sphereRegFsLRInitAffineXfms{h} = fpp.bids.changeName(sphereRegPaths{h},{'space','den','desc','from','to'},...
        {[],[],'wbcmdAffine','fsnative','fsLR'},'xfm','.mat');
    fpp.wb.command('surface-sphere-project-unproject',sphereRegPaths{h},...
        [anatPreprocDir '/hemi-' Hemis{h} '_space-fsaverage_den-164k_sphere.surf.gii'],...
        [anatPreprocDir '/hemi-' Hemis{h} '_space-fsaverage_den-164k_desc-reg2fsLR_sphere.surf.gii'],...
        sphereRegFsLRInitPaths{h});
    
    % Compute fsnative -> fsLR affine transformation for initialization
    fpp.wb.command('surface-affine-regression',spherePaths{h},sphereRegFsLRInitPaths{h},sphereRegFsLRInitAffineXfms{h});
    fpp.wb.command('surface-apply-affine',spherePaths{h},sphereRegFsLRInitAffineXfms{h},sphereRegFsLRInitAffinePaths{h});
    fpp.wb.command('surface-modify-sphere',sphereRegFsLRInitAffinePaths{h},'100',sphereRegFsLRInitAffinePaths{h});
    
    % Compute MSM-based registration
    if ~exist([msmDir '/sub-' subjID '_hemi-' Hemis{h} '_desc-msm_sphere.reg.surf.gii'],'file') %%% TEMPORARY FOR DEBUGGING
        fpp.util.system(['/usr/local/bin/msm --conf=' dataDir '/MSMSulcStrainFinalconf'...
            ' --inmesh=' sphereRegFsLRInitAffinePaths{h}...
            ' --refmesh=' fsLRSpherePaths{h}{2}...
            ' --indata=' sulcPaths{h}...
            ' --refdata=' anatPreprocDir '/hemi-' Hemis{h} '_space-fsLR_den-164k_desc-AtlasRef_sulc.shape.gii'...
            ' --out=' msmDir '/sub-' subjID '_hemi-' Hemis{h} '_desc-msm_']);
    end
    system(['cp ' msmDir '/sub-' subjID '_hemi-' Hemis{h} '_desc-msm_sphere.reg.surf.gii ' sphereRegFsLRPaths{h}]);
    fpp.wb.command('set-structure',sphereRegFsLRPaths{h},structures{h});
    fpp.bids.jsonReconstruct(spherePaths{h},sphereRegFsLRPaths{h});
    
    % Compute areal/edge distortion from MSMSulc registration
    arealDistortionPaths{h} = fpp.bids.changeName(sulcPaths{h},'desc','reg2fsLRareal','distortion');
    edgeDistortionPaths{h} = fpp.bids.changeName(sulcPaths{h},'desc','reg2fsLRedge','distortion');
    fpp.wb.command('surface-distortion',spherePaths{h},sphereRegFsLRPaths{h},arealDistortionPaths{h});
    fpp.wb.command('surface-distortion',spherePaths{h},sphereRegFsLRPaths{h},edgeDistortionPaths{h},'-edge-method');
    
    % Take union of cortex ROI from subject and atlas
    maskAtlasPaths{h} = fpp.bids.changeName(maskPaths{h},'desc','cortexAtlas','mask');
    fpp.wb.command('metric-resample',...
        [anatPreprocDir '/hemi-' Hemis{h} '_space-fsLR_den-164k_desc-cortexAtlas_mask.shape.gii'],...
        [fsLRSpherePaths{h}{2} ' ' sphereRegFsLRPaths{h} ' BARYCENTRIC'],maskAtlasPaths{h},'-largest');
    fpp.wb.command('metric-math',[],'(atlas + indiv) > 0',maskPaths{h},...
        ['-var atlas ' maskAtlasPaths{h} ' -var indiv ' maskPaths{h}]);
    fpp.wb.command('metric-mask',thicknessPaths{h},maskPaths{h},thicknessPaths{h});
    fpp.wb.command('metric-mask',curvPaths{h},maskPaths{h},curvPaths{h});
    
    % Define medial wall ROI (1 - cortex), convert to label
    parcPaths{h}{end+1} = fpp.bids.changeName(maskPaths{h},'desc','medialwall','dseg','.label.gii');
    fpp.wb.command('metric-math',[],'1 - var',fpp.bids.changeName(maskPaths{h},'desc','medialwall'),...
        ['-var var ' maskPaths{h}]);
    fpp.wb.command('metric-label-import',fpp.bids.changeName(maskPaths{h},'desc','medialwall'),...
        [anatPreprocDir '/desc-medialwall_lut.txt'],parcPaths{h}{end});
    parcPaths{h}{end+1} = fpp.bids.changeName(maskAtlasPaths{h},'desc','medialwallAtlas','dseg','.label.gii');
    fpp.wb.command('metric-math',[],'1 - var',fpp.bids.changeName(maskAtlasPaths{h},'desc','medialwallAtlas'),...
        ['-var var ' maskAtlasPaths{h}]);
    fpp.wb.command('metric-label-import',fpp.bids.changeName(maskAtlasPaths{h},'desc','medialwallAtlas'),...
        [anatPreprocDir '/desc-medialwall_lut.txt'],parcPaths{h}{end});
    % Atlas ROI in fsLR space
    maskAtlasFSLRPaths{h} = [anatPreprocDir '/hemi-' Hemis{h} '_space-fsLR_den-32k_desc-cortexAtlas_mask.shape.gii'];
    parcFSLRPaths{h}{1} = fpp.bids.changeName(maskAtlasFSLRPaths{h},'desc','medialwallAtlas','dseg','.label.gii');
    fpp.wb.command('metric-math',[],'1 - var',fpp.bids.changeName(maskAtlasFSLRPaths{h},'desc','medialwallAtlas'),...
        ['-var var ' maskAtlasFSLRPaths{h}]);
    fpp.wb.command('metric-label-import',fpp.bids.changeName(maskAtlasFSLRPaths{h},'desc','medialwallAtlas'),...
        [anatPreprocDir '/desc-medialwall_lut.txt'],parcFSLRPaths{h}{end});
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 10: Resample to fsLR
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 10, Resample to fsLR                      - ' subjID]);
surfaces = {'white','pial','midthickness'};
parcs = {'aparc','aparc.a2009s','medialwall','medialwallAtlas'};
for h=1:2
    % Resample individual-space surfaces to fsLR coordinates
    for s=1:length(surfaces)
        inputPath = fpp.bids.changeName(midthickPaths{h},'','',surfaces{s});
        outputPath = fpp.bids.changeName(inputPath,'den','32K');
        fpp.wb.command('surface-resample',inputPath,[sphereRegFsLRPaths{h} ' '...
            fsLRSpherePaths{h}{1} ' BARYCENTRIC'],outputPath);
        eval([strrep(surfaces{s},'ness','') 'FsLRPaths{h} = outputPath;']);
    end
    % Generate inflated surface
    fsLRInflationScale = .75;
    fpp.wb.command('surface-generate-inflated',midthickFsLRPaths{h},fpp.bids.changeName(midthickFsLRPaths{h},[],[],'inflated'),...
        fpp.bids.changeName(midthickFsLRPaths{h},[],[],'vinflated'),['-iterations-scale ' num2str(fsLRInflationScale)]);
    % Resample shape files
    for s=1:length(shapes)
        inputPath = fpp.bids.changeName(sulcPaths{h},'','',shapes{s});
        outputPath = fpp.bids.changeName(inputPath,{'space','den'},{'fsLR','32K'});
        fpp.wb.command('metric-resample',inputPath,[sphereRegFsLRPaths{h} ' ' fsLRSpherePaths{h}{1}...
            ' ADAP_BARY_AREA'],outputPath,['-area-surfs ' midthickPaths{h} ' ' midthickFsLRPaths{h}...
            ' -current-roi ' maskPaths{h}]);
        fpp.wb.command('metric-mask',outputPath,[anatPreprocDir '/hemi-' Hemis{h} ...
            '_space-fsLR_den-32k_desc-cortexAtlas_mask.shape.gii'],outputPath);
    end
    outputPath = fpp.bids.changeName(arealDistortionPaths{h},{'space','den'},{'fsLR','32K'});
    fpp.wb.command('metric-resample',arealDistortionPaths{h},[sphereRegFsLRPaths{h} ' ' fsLRSpherePaths{h}{1}...
        ' ADAP_BARY_AREA'],outputPath,['-area-surfs ' midthickPaths{h} ' ' midthickFsLRPaths{h}]);
    outputPath = fpp.bids.changeName(edgeDistortionPaths{h},{'space','den'},{'fsLR','32K'});
    fpp.wb.command('metric-resample',edgeDistortionPaths{h},[sphereRegFsLRPaths{h} ' ' fsLRSpherePaths{h}{1}...
        ' ADAP_BARY_AREA'],outputPath,['-area-surfs ' midthickPaths{h} ' ' midthickFsLRPaths{h}]);
    outputPath = fpp.bids.changeName(maskPaths{h},{'space','den'},{'fsLR','32K'});
    fpp.wb.command('metric-resample',maskPaths{h},[sphereRegFsLRPaths{h} ' ' fsLRSpherePaths{h}{1}...
        ' ADAP_BARY_AREA'],outputPath,['-area-surfs ' midthickPaths{h} ' ' midthickFsLRPaths{h}]);
    outputPath = fpp.bids.changeName(maskAtlasPaths{h},{'space','den'},{'fsLR','32K'});
    fpp.wb.command('metric-resample',maskAtlasPaths{h},[sphereRegFsLRPaths{h} ' ' fsLRSpherePaths{h}{1}...
        ' ADAP_BARY_AREA'],outputPath,['-area-surfs ' midthickPaths{h} ' ' midthickFsLRPaths{h}]);
    % Resample label files
    for p=1:length(parcs)
        if sum(regexp(parcs{p},'medialWallAtlas'))>0, continue; end     % Don't resample medialWallAtlas - already exists in fsLR space
        outputPath = fpp.bids.changeName(parcPaths{h}{p},{'space','den'},{'fsLR','32K'});
        fpp.wb.command('label-resample',parcPaths{h}{p},[sphereRegFsLRPaths{h} ' '...
            fsLRSpherePaths{h}{1} ' BARYCENTRIC'],outputPath,'-largest');
    end
    % Generate midthickness vertex area map
    outputPath = fpp.bids.changeName(midthickFsLRPaths{h},{'space','desc'},{'fsLR','midthickness'},'varea','.shape.gii');
    fpp.wb.command('surface-vertex-areas',midthickFsLRPaths{h},[],outputPath);
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 11: Generate CIFTI metric/label files
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 11, Generate CIFTI metric/label files     - ' subjID]);
spaces = {'individual','fsLR'};
densities = {'native','32k'};
metrics = {'sulc','thickness','curv','distortion','distortion','mask'};    % Metric files to convert to CIFTI
mapNames = {'Sulc','Thickness','Curvature','ArealDistortionMSMSulc','EdgeDistortionMSMSulc','ROI'};
descs = {'','','','reg2fsLRareal','reg2fsLRedge','cortex'};
paletteStrings = {'-pos-percent 2 98 -palette-name Gray_Interp -disp-pos true -disp-neg true -disp-zero true',...
    '-pos-percent 4 96 -interpolate true -palette-name videen_style -disp-pos true -disp-neg false -disp-zero false',...
    '-pos-percent 2 98 -palette-name Gray_Interp -disp-pos true -disp-neg true -disp-zero true',...
    '-pos-user 0 1 -neg-user 0 -1 -interpolate true -palette-name ROY-BIG-BL -disp-pos true -disp-neg true -disp-zero false',...
    '-pos-user 0 1 -neg-user 0 -1 -interpolate true -palette-name ROY-BIG-BL -disp-pos true -disp-neg true -disp-zero false',...
    '-pos-user 0 1 -neg-user 0 -1 -interpolate false -palette-name Gray_Interp -disp-pos true -disp-neg false -disp-zero false'};
modes = {'MODE_AUTO_SCALE_PERCENTAGE','MODE_AUTO_SCALE_PERCENTAGE','MODE_AUTO_SCALE_PERCENTAGE',...
    'MODE_USER_SCALE','MODE_USER_SCALE','MODE_USER_SCALE'};
for s=1:length(spaces)
    maskPathL = fpp.bids.changeName(maskAtlasPaths{1},{'space','den'},{spaces{s},densities{s}});
    maskPathR = fpp.bids.changeName(maskPathL,'hemi','R');
    maskStrL = [' -roi-left ' maskPathL];
    maskStrR = [' -roi-right ' maskPathR];
    for m=1:length(metrics)
        inputPathL = fpp.bids.changeName(sulcPaths{1},{'space','den','desc'},...
            {spaces{s},densities{s},descs{m}},metrics{m});
        inputPathR = fpp.bids.changeName(inputPathL,'hemi','R');
        outputPath = fpp.bids.changeName(inputPathL,'hemi',[],metrics{m},'.dscalar.nii');
        fpp.wb.command('cifti-create-dense-scalar',[],[],outputPath,['-left-metric '...
            inputPathL maskStrL ' -right-metric ' inputPathR maskStrR]);
        fpp.wb.command('set-map-names',outputPath,[],[],['-map 1 ' subjID '_' mapNames{m}]);
        fpp.wb.command('cifti-palette',outputPath,modes{m},outputPath,paletteStrings{m});
    end
    for p=1:length(parcs)
        if strcmp(parcs{p},'medialwallAtlas') && strcmp(spaces{s},'fsLR')   % No subject label for medialwallAtlas file in fsLR space
            inputPathL = parcFSLRPaths{1}{1};
            inputPathR = parcFSLRPaths{2}{1};
        else
            inputPathL = fpp.bids.changeName(parcPaths{1}{p},{'space','den'},{spaces{s},densities{s}});
            inputPathR = fpp.bids.changeName(inputPathL,'hemi','R');
        end
        if sum(regexp(parcs{p},'medialwall'))>0, maskStrL = ''; maskStrR = ''; end   % Don't mask medial wall label
        outputPath = fpp.bids.changeName(inputPathL,'hemi',[],'dseg','.dlabel.nii');
        fpp.wb.command('cifti-create-label',[],[],outputPath,['-left-label '...
            inputPathL maskStrL ' -right-label ' inputPathR maskStrR]);
        fpp.wb.command('set-map-names',outputPath,[],[],['-map 1 ' subjID '_' parcs{p}]);
    end
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 11.5, Copy/resample HCP1200 atlas data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 11.5, Copy/resample HCP1200 atlas data    - ' subjID]);
hcpAtlasDir = [dataDir '/HCP_S1200_Atlas'];
if exist(hcpAtlasDir,'dir')
    hcpDirExists = 1;
    surfaces = {'white','pial','midthickness','inflated','vinflated','flat','sphere'};
    surfacesHCP = surfaces; surfacesHCP{5} = 'very_inflated';
    surfacesHCPSuffix = {'_MSMAll','_MSMAll','_MSMAll','_MSMAll','_MSMAll','',''};
    parcFiles = {'Human.MedialWall_Conte69.32k_fs_LR.dlabel.nii',...
        'Q1-Q6_RelatedValidation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii',...
        'RSN-networks.32k_fs_LR.dlabel.nii','Gordon333.32k_fs_LR.dlabel.nii'};
    parcNames = {'medialwallConte69','MMP','RSN','Gordon'};
    borderFiles = {'Q1-Q6_RelatedValidation210.L.CorticalAreas_dil_Final_Final_Areas_Group.32k_fs_LR.border',...
        'Q1-Q6_RelatedValidation210.R.CorticalAreas_dil_Final_Final_Areas_Group.32k_fs_LR.border'};
    templatePath = fpp.bids.changeName(sulcPaths{1},{'hemi','space','den'},...
        {[],'individual','native'},'sulc','.dscalar.nii'); % Registration template
    for h=1:2                   % Surfaces
        for s=1:length(surfaces)
            fpp.util.system(['cp ' hcpAtlasDir '/S1200.' Hemis{h} '.' surfacesHCP{s} surfacesHCPSuffix{s}...
                '.32k_fs_LR.surf.gii ' fpp.bids.changeName(midthickPaths{h},{'sub','space','den','desc'},...
                {[],'fsLR','32k','HCP1200Atlas'},surfaces{s})]);
        end
    end
    for s=1:length(shapes)      % Shape files
        outputPath=fpp.bids.changeName(sulcPaths{h},{'sub','hemi','space','den','desc'},...
             {[],[],'fsLR','32k','HCP1200Atlas'},shapes{s},'.dscalar.nii');
        outputPathNative=fpp.bids.changeName(outputPath,{'sub','space','den'},{subjID,'individual','native'});
        fpp.util.system(['cp ' hcpAtlasDir '/S1200.' lower(mapNames{s}) '_MSMAll.32k_fs_LR.dscalar.nii ' outputPath]);
        fpp.wb.command('cifti-resample',outputPath,['COLUMN ' templatePath ' COLUMN ADAP_BARY_AREA TRILINEAR'],...
            outputPathNative,['-left-spheres ' fsLRSpherePaths{1}{1} ' ' sphereRegFsLRPaths{1} ' '...
            '-left-area-surfs ' fpp.bids.changeName(midthickPaths{1},{'sub','space','den','desc'},...
            {[],'fsLR','32k','HCP1200Atlas'}) ' ' midthickPaths{1} ' '...
            '-right-spheres ' fsLRSpherePaths{2}{1} ' ' sphereRegFsLRPaths{2} ' '...
            '-right-area-surfs ' fpp.bids.changeName(midthickPaths{2},{'sub','space','den','desc'},...
            {[],'fsLR','32k','HCP1200Atlas'}) ' ' midthickPaths{2}]);
        fpp.wb.command('cifti-math',[],'metric * mask',outputPathNative,['-var metric ' outputPathNative...
            ' -var mask ' fpp.bids.changeName(maskPaths{1},'hemi',[],[],'.dscalar.nii')]);  % Mask with cortex ROI
    end
    for p=1:length(parcNames)   % Parcellations
        outputPath=fpp.bids.changeName(sulcPaths{h},{'sub','space','den','desc','hemi'},...
            {[],'fsLR','32k',parcNames{p},''},'dseg','.dlabel.nii');
        outputPathNative=fpp.bids.changeName(outputPath,{'sub','space','den'},{subjID,'individual','native'});
        if sum(regexp(parcs{p},'medialwall'))>0 % For medial wall labels, use un-masked template CIFTI
            templatePath2 = fpp.bids.changeName(templatePath,'desc','medialWall','dseg','.dlabel.nii');
        else
            templatePath2 = templatePath;
        end
        disp([outputPath ' ' templatePath2]);   % FOR DEBUGGING
        fpp.util.system(['cp ' hcpAtlasDir '/' parcFiles{p} ' ' outputPath]);
        fpp.wb.command('cifti-resample',outputPath,['COLUMN ' templatePath2 ' COLUMN BARYCENTRIC TRILINEAR'],...
            outputPathNative,['-left-spheres ' fsLRSpherePaths{1}{1} ' ' sphereRegFsLRPaths{1} ' '...
            '-right-spheres ' fsLRSpherePaths{2}{1} ' ' sphereRegFsLRPaths{2} ' -surface-largest']);
        % Convert parc to volume
        if sum(regexp(parcNames{p},'medialwall'))==0
            parcVolPath = fpp.bids.changeName(outputPath,{'sub','space','den'},{subjID,'individual',[]},[],'.nii.gz');
            parcLUTPath = [anatPreprocDir '/desc-' parcNames{p} '_lut.txt'];
            for h=1:2
                parcSurfPaths{h} = fpp.bids.changeName(outputPath,'hemi',Hemis{h},[],'.label.gii');
                parcVolPaths{h} = fpp.bids.changeName(outputPath,{'hemi','den'},{Hemis{h},''},[],'.nii.gz');
            end
            fpp.wb.command('cifti-separate',outputPath,'COLUMN',[],['-label CORTEX_LEFT '...
                parcSurfPaths{1} ' -label CORTEX_RIGHT ' parcSurfPaths{2}]);
           for h=1:2
               fpp.wb.command('label-to-volume-mapping',parcSurfPaths{h},[fpp.bids.changeName(midthickPaths{h},{'space','den'},...
                   {'individual','32k'}) ' ' inputT1Path],parcVolPaths{h},['-ribbon-constrained '...
                   fpp.bids.changeName(midthickPaths{h},{'space','den'},{'individual','32k'},'white') ' '...
                   fpp.bids.changeName(midthickPaths{h},{'space','den'},{'individual','32k'},'pial')]);
           end
           fpp.fsl.maths(parcVolPaths{1},['-add ' parcVolPaths{2}],parcVolPath);
           fpp.wb.command('cifti-label-export-table',outputPath,'1',parcLUTPath);
           fpp.wb.command('volume-label-import',parcVolPath,parcLUTPath,parcVolPath,'-drop-unused-labels');
           for h=1:2, fpp.util.system(['rm -rf ' parcSurfPaths{h} ' ' parcVolPaths{h}]); end
        end
    end
    for h=1:2                   % Border files
        outputPath = fpp.bids.changeName(sulcPaths{h},{'sub','space','den','desc'},...
            {[],'fsLR','32k','MMP'},'dseg','.border');
        outputPathNative=fpp.bids.changeName(outputPath,{'sub','space','den'},{subjID,'individual','native'});
        fpp.util.system(['cp ' hcpAtlasDir '/' borderFiles{h} ' ' outputPath]);
        fpp.wb.command('border-resample',outputPath,[fsLRSpherePaths{h}{1} ' ' sphereRegFsLRPaths{h}],outputPathNative);
    end
    fpp.util.system(['cp ' hcpAtlasDir '/MMP_areas_tangential_32k_bothHems_inflated.wb_annot '...
        anatPreprocDir '/space-fsLR_den-32k_desc-MMPAreas_inflated.wb_annot']);
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% STEP 12: Generate spec files
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('%s\n',['Step 12, Generate spec files                   - ' subjID]);
volumeFiles = {inputT1Path,inputT1Path,standardPath2mmBrain};     % Add MNI-registered anatomical volumes for third space
volumeFiles2 = {inputT2Path,inputT2Path,[]};    % Add MNI-registered anatomical volumes for third space
surfaceSpaces = {'individual','individual','fsLR'};
surfaceDensities = {'native','32k','32k'};
surfaceSubjIDs = {subjID,subjID,[]};
surfaceDescs = {[],[],'HCP1200Atlas'};
surfaces = {'white','pial','midthickness','inflated','vinflated'};
sphereSpaces = {'individual','fsLR','fsLR'};
sphereSubjIDs = {subjID,[],[]};
sphereDensities = {'native','32k','32k'};
metricSpaces = {'individual','fsLR','fsLR'};
metrics = {'sulc','thickness','curv','distortion','distortion','mask','sulc','thickness','curv'};    % Metric files to add to specs
metricDescs = {'','','','reg2fsLRareal','reg2fsLRedge','cortex','HCP1200Atlas','HCP1200Atlas','HCP1200Atlas'};              % Metric descriptions
parcNames = {'medialwall','medialwallAtlas','aparc','aparc.a2009s','medialwallConte69','MMP','RSN','Gordon'};
if ~hcpDirExists
    surfaceSpaces = surfaceSpaces(1:2); % Only use S1200 space if atlas files exist
    metrics = metrics(1:5);
    parcNames = parcNames(1:4);
end
for s=1:length(surfaceSpaces)
    specPath = fpp.bids.changeName(midthickPaths{1},{'hemi','space','den'},{[],surfaceSpaces{s},...
        surfaceDensities{s}},'brain','.spec');
    if overwrite && exist(specPath,'file'), fpp.util.system(['rm -rf ' specPath]); end
    % Add volumes
    if ~isempty(volumeFiles{s})
        fpp.wb.command('add-to-spec-file',specPath,'INVALID',volumeFiles{s});
    end
    if ~isempty(volumeFiles2{s})
        fpp.wb.command('add-to-spec-file',specPath,'INVALID',volumeFiles2{s});
    end
    % Add surfaces
    for h=1:2
        for i=1:length(surfaces)
            fpp.wb.command('add-to-spec-file',specPath,structures{h},fpp.bids.changeName(midthickPaths{h},...
                {'sub','space','den','desc'},{surfaceSubjIDs{s},surfaceSpaces{s},surfaceDensities{s},surfaceDescs{s}},surfaces{i}));
        end
        if strcmp(surfaceSpaces{s},'fsLR') &&  strcmp(surfaceDensities{s},'32k')    % Include flatmap in atlas space
            fpp.wb.command('add-to-spec-file',specPath,structures{h},fpp.bids.changeName(midthickPaths{h},...
                {'sub','space','den','desc'},{surfaceSubjIDs{s},surfaceSpaces{s},surfaceDensities{s},surfaceDescs{s}},'flat'));
        end
        % Add spheres
        fpp.wb.command('add-to-spec-file',specPath,structures{h},fpp.bids.changeName(midthickPaths{h},...
            {'sub','space','den'},{sphereSubjIDs{s},sphereSpaces{s},sphereDensities{s}},'sphere'));
        if strcmp(surfaceSpaces{s},'individual') &&  strcmp(surfaceDensities{s},'native')   % Registration sphere
            fpp.wb.command('add-to-spec-file',specPath,structures{h},fpp.bids.changeName(midthickPaths{h},...
                {'sub','space','den','desc'},{sphereSubjIDs{s},sphereSpaces{s},sphereDensities{s},'reg2fsLR'},'sphere'));
        end
    end
    % Add CIFTI metric files
    for i=1:length(metrics)
        subLabel = subjID;
        if strcmp(metricDescs{i},'HCP1200Atlas') && strcmp(metricSpaces{s},'fsLR'), subLabel = ''; end
        fpp.wb.command('add-to-spec-file',specPath,'INVALID',fpp.bids.changeName(sulcPaths{1},...
            {'sub','hemi','space','den','desc'},{subLabel,[],metricSpaces{s},surfaceDensities{s},...
            metricDescs{i}},metrics{i},'.dscalar.nii'));
    end
    % Add CIFTI label files
    for i=1:length(parcNames)
        subLabel = subjID;
        if ismember(parcNames{i},{'medialwallAtlas','medialwallConte69','MMP','RSN','Gordon'}) ...
                && strcmp(metricSpaces{s},'fsLR'), subLabel = ''; end
        fpp.wb.command('add-to-spec-file',specPath,'INVALID',fpp.bids.changeName(sulcPaths{1},...
            {'sub','hemi','space','den','desc'},{subLabel,[],metricSpaces{s},surfaceDensities{s},...
            parcNames{i}},'dseg','.dlabel.nii'));
    end
    % Add border/annot files
    if hcpDirExists
        % Border
        for h=1:2
            if strcmp(surfaceDensities{s},'32k')
                subLabel = '';
            else
                subLabel = subjID;
            end
            fpp.wb.command('add-to-spec-file',specPath,'INVALID',fpp.bids.changeName(sulcPaths{h},...
                {'sub','space','den','desc'},{subLabel,metricSpaces{s},surfaceDensities{s},'MMP'},'dseg','.border'));
        end
        % Annot
        if strcmp(surfaceSpaces{s},'fsLR')
            fpp.wb.command('add-to-spec-file',specPath,'INVALID',[anatPreprocDir ...
                '/space-fsLR_den-32k_desc-MMPAreas_inflated.wb_annot']);
        end
    end
end



% TODO HERE:
% - Generate GM/WM/CSF masks
% - Generate myelin map



%%% CLEANUP HERE
% - Delete unneeded transforms
% - sphereRegFsLRInitPaths{h}
% - sphereRegFsLRInitAffinePaths{h}
% - sphereRegFsLRInitAffineXfms{h}
% - fpp.bids.changeName(maskPaths{h},'desc','medialwall') - medial wall metric file




end