
% Function to apply motion and distortion correct, and registration to
% functional template with a single interpolation step.

function oneShotMotionDistortionCorrect(inputPaths,outputPaths,funcTemplatePath,funcTemplateName,mcDir,topupWarpPath,...
    topupJacobianPath,xfmNativeFunc2FuncTemplate,xfmSpinEcho2NativeFunc,xfmNativeFunc2SpinEcho)

keyboard;

xfmSpinEcho2FuncTemplate = fpp.bids.changeName(funcTemplatePath,{'desc','from','to','mode'},...
    {'','SpinEcho',funcTemplateName,'image'},'xfm','.mat');
topupJacobian2FuncTemplatePath = fpp.bids.changeName(topupJacobianPath,'space',funcTemplateName,'jacobian');

% Move warp Jacobian to FuncTemplate space
system(['convert_xfm -omat ' xfmSpinEcho2FuncTemplate ' -concat ' xfmNativeFunc2FuncTemplate xfmSpinEcho2NativeFunc]);
system(['flirt -in ' topupJacobianPath ' -ref ' funcTemplatePath ' -out ' topupJacobian2FuncTemplatePath ...
    ' -applyxfm -init ' xfmSpinEcho2FuncTemplate]);

for e=1:length(outputPaths)
    mergeCmd = ['fslmerge -tr ' outputPaths{e}];
    inputSplitStem = [strrep(inputPaths{e},'.nii.gz','') '_SplitForMoco'];
    outputSplitStem = [strrep(fpp.bids.changeName(inputPaths{e},'space',funcTemplateName),'.nii.gz','') '_SplitForMoco'];
    system(['fslsplit ' inputPaths{e} ' ' inputSplitStem ' -t']);
    for t=0:vols-1
        inputVolPath = [inputSplitStem numpad(t,4) '.nii.gz'];
        outputVolPath = [outputSplitStem numpad(t,4) '.nii.gz'];
        system(['convert_xfm -omat ' xfmSpinEcho2FuncTemplate ' -concat ' xfmNativeFunc2FuncTemplate ' ' xfmSpinEcho2NativeFunc]);
        xfmInputVol2NativeFunc = [mcDir '/' fpp.bids.changeName(outputPaths{e},{'desc','from','to','mode'},...
            {'',['orig' matFiles(f).name(5:end)],'orig','image'},'xfm','.mat')];
        xfmInputVol2SpinEcho = [mcDir '/' fpp.bids.changeName(outputPaths{e},{'desc','from','to','mode'},...
            {'',['orig' matFiles(f).name(5:end)],'SpinEcho','image'},'xfm','.mat')];
        system(['convert_xfm -omat ' xfmInputVol2SpinEcho ' -concat ' xfmNativeFunc2SpinEcho xfmInputVol2NativeFunc]);
        % Single-shot application of motion correction, undistortion, and registration to FuncTemplate
        system(['applywarp --in=' inputVolPath ' --ref=' funcTemplatePath ' --out=' outputVolPath ...
            ' --warp=' topupWarpPath ' --premat=' xfmInputVol2SpinEcho ' --postmat=' xfmSpinEcho2FuncTemplate]);
        system(['fslmaths ' outputVolPath ' -mul ' topupJacobian2FuncTemplatePath ' ' outputVolPath]);
        mergeCmd = [mergeCmd ' ' outputVolPath];
    end
    
    % Merge output into single time series file, delete individual time points
    mergeCmd = [mergeCmd ' ' num2str(tr)];
    system(mergeCmd);
    system(['rm -rf ' inputSplitStem '*.nii.gz ' outputSplitStem '*.nii.gz']);
    
    % Generate output JSON file
    [~,~,inputExt] = filepartsGZ(inputPaths{e});
    inputJsonPath = strrep(inputPaths{e},inputExt,'.json');
    [~,~,outputExt] = filepartsGZ(outputPaths{e});
    outputJsonPath = strrep(outputPaths{e},outputExt,'.json');
    jsonReconstruct(inputJsonPath,outputJsonPath);
    bidsBaseDir = fpp.bids.checkBidsDir(inputPaths{e});
    sources = inputPaths{e};
    if ~isempty(bidsBaseDir)
        sources = strrep(sources,bidsBaseDir,'');
    end
    fpp.bids.jsonChangeValue(outputJsonPath,{'Description','Sources','SpatialReference'},...
        {['Partially preprocessed data generated by fmriPermPipe, saved after motion correction, '...
        ' distortion, and functional template registration step.'],...
        sources,funcTemplateName});
end

end